"""pv cicd — generate CI/CD configuration for PromptView."""

from pathlib import Path
from typing import Optional

import typer

from ..output import console

app = typer.Typer(
    name="cicd",
    help="Generate CI/CD configuration for PromptView.",
    no_args_is_help=True,
)

_GITHUB_ACTIONS_YAML = """\
# PromptView CI/CD — auto-generated by `pv cicd generate`
# Checks that all prompts are tracked and no metric regressions on PRs.
name: PromptView Check

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  prompt-check:
    name: Prompt Version Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PromptView
        run: pip install promptview

      - name: Initialize PromptView
        run: pv init --no-scan

      - name: Scan for untracked prompts
        run: pv scan --fail-on-untracked

      # Optional: run evals if test cases exist
      # Uncomment and set your API key secret to enable metric regression checks
      # - name: Run eval regression check
      #   run: pv eval tests/prompt_tests.jsonl --fail-on-regression 0.05
      #   env:
      #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
"""


@app.command("generate")
def generate_command(
    output: Optional[Path] = typer.Option(
        None,
        "--output",
        "-o",
        help="Write the YAML to this file path instead of printing to stdout.",
    ),
    platform: str = typer.Option(
        "github",
        "--platform",
        help="Target CI/CD platform. Currently only 'github' is supported.",
    ),
) -> None:
    """Generate a CI/CD workflow file for PromptView prompt checks."""
    if platform != "github":
        console.print(
            f"[red]✗ Unsupported platform '{platform}'. "
            "Only 'github' is currently supported.[/red]"
        )
        raise typer.Exit(1)

    yaml_content = _GITHUB_ACTIONS_YAML

    if output is not None:
        output = output.resolve()
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(yaml_content)
        console.print(f"[green]✓ Written to {output}[/green]")
    else:
        try:
            from rich.syntax import Syntax
            syntax = Syntax(yaml_content, "yaml", theme="monokai", line_numbers=False)
            console.print(syntax)
        except Exception:
            # Fallback to plain print if Rich Syntax is unavailable
            console.print(yaml_content)
